PAWeb/Controllers/DepartmentController.cs
using PADomain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PAWeb
{
    public class DepartmentController : Controller
    {
        private IUnitOfWork _uow;
        public DepartmentController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Department
        [HttpGet]
        public ActionResult DepartmentCorner()
        {
            var currentdepartment = _uow.Departments.GetAll();

            var dvm = new DeptListViewModel
            {

                AllDepartment = currentdepartment

            };
            return View(dvm);
        }

    }
}

PAWeb/Controllers/EventController.cs
using PADomain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PAWeb
{
    public class EventController : Controller
    {
        IUnitOfWork _uow;
        public EventController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        // GET: Event
        public ActionResult EventDetails(int id)
        {
            var _event = _uow.Events.Get(id);
            Event singleevent = _event;

            return View(singleevent);
        }

        public ActionResult UpcomingEvents()
        {
            var upcomingevent = _uow.Events.GetAll();
            var hvm = new EventViewModel
            {
                Events = upcomingevent

            };
            return View(hvm);
        }
        public ActionResult EventCalendar()
        {
            var eventcalendar = _uow.Events.GetAll();
            var evm = new EventViewModel
            {
                Events = eventcalendar
            };
            return View(evm);
        }
        //public ActionResult EventbyCategory(string name)
        //{

        //    var sermonscategory = _uow.Events.Find(sc => sc.e.SermonName == name);

        //    var svm = new SermonViewModel
        //    {
        //        Sermons = sermonscategory,
        //        SermonCategory = name

        //    };
        //    return View("Index", svm);
        //}

    }
}

PAWeb/Controllers/SermonController.cs
using PADomain;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PAWeb
{
    public class SermonController : Controller
    {
        IUnitOfWork _uow;
        public SermonController(IUnitOfWork uow)
        {
            _uow = uow;
        }
      public ActionResult Index()
        {
            var sermon = _uow.Sermons.GetAll();
            ViewBag.SermonCategory = _uow.SermonCategories.GetAll().Select(r => new SermonCategory
            {
                SermonName = r.SermonName,
                SermonDescription = r.SermonDescription
            });
            var sermonCat = _uow.SermonCategories.GetAll();
            var svm = new SermonViewModel
            {
                Sermons = sermon,
                SermonCategory = sermonCat,
                SermonCat = ""
            };
            return View(svm);
        }
        public ActionResult SermonsbyCategory(string name)
        {

            var sermonscategory = _uow.Sermons.Find(sc => sc.SermonCategory.SermonName == name);
            var svm = new SermonViewModel
            {
                Sermons = sermonscategory,
                //SermonCategory = name
                SermonCat = name
            };
            return View("Index", svm);
        }
        public ActionResult SermonDetails(Sermon sermon, int id)
        {
            var _sermon = _uow.Sermons.Get(id);
            var civm = new SermonIndexViewModel
            {
                sermon = _sermon
            };
            return View(civm);
        }
        public ActionResult PrintPdf(Sermon s, int id)
        {
            var _sermon = _uow.Sermons.Get(id);
            var sivm = new SermonIndexViewModel
            {
                sermon = _sermon,
                ReturnUrl = ""
            };
            var pdfView = new ViewAsPdf("SermonDetails", sivm)
            {
                FileName = sivm.sermon.Title,
                PageSize = Rotativa.Options.Size.A4,
                PageMargins =
                {
                    Left=0,
                    Right=0
                }
            };
            return pdfView;
        }
    }
}

PAWeb/Controllers/WorkerController.cs
using PADomain;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using PADomain.WorkerFiles;
using System.Web;
using System.Web.Mvc;

namespace PAWeb
{
    public class WorkerController : Controller
    {
        private IUnitOfWork _uow;
        public WorkerController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public ActionResult Views()
        {
            var dept = _uow.Departments.GetAll().Select(r => r.Name);
            ViewBag.Department = new SelectList(dept);
            return View(new WorkersViewModel());
        }
        // GET: Worker
       
        [HttpGet]
        public ActionResult JoinWorker()
        {
            var dept = _uow.Departments.GetAll().Select(r => r.Name);
            ViewBag.Department = new SelectList(dept);
            return View(new WorkersViewModel());
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult JoinWorker(WorkersViewModel dcvm)
        {
            
            if (ModelState.IsValid)
            {
                var dept = _uow.Departments.Find(r => r.Name == dcvm.DepartmentName).FirstOrDefault();

                string fileName = Path.GetFileNameWithoutExtension(dcvm.ImageFile.FileName);
                string extension = Path.GetExtension(dcvm.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
                dcvm.ImageUrl = fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                dcvm.ImageFile.SaveAs(fileName);

                if(dcvm.SODCert != null )
                {
                    string SODfile = Path.GetFileNameWithoutExtension(dcvm.SODCert.FileName);
                    string SODfileextension = Path.GetExtension(dcvm.SODCert.FileName);
                    SODfile = SODfile + DateTime.Now.ToString("yymmssffff") + SODfileextension;
                    dcvm.SODUrl = SODfile;
                    SODfile = Path.Combine(Server.MapPath("~/Content/Images/"), SODfile);
                    dcvm.SODCert.SaveAs(SODfile);
                }
                
                if(dcvm.BCCert != null)
                {
                    string BCfile = Path.GetFileNameWithoutExtension(dcvm.BCCert.FileName);
                    string BCfileextension = Path.GetExtension(dcvm.BCCert.FileName);
                    BCfile = BCfile + DateTime.Now.ToString("yymmssffff") + BCfileextension;
                    dcvm.BCUrl = BCfile;
                    BCfile = Path.Combine(Server.MapPath("~/Content/Images/"), BCfile);
                    dcvm.BCCert.SaveAs(BCfile);

                }
                if(dcvm.BaptismCert != null)
                {
                    string Baptismfile = Path.GetFileNameWithoutExtension(dcvm.BaptismCert.FileName);
                    string Baptismfileextension = Path.GetExtension(dcvm.BaptismCert.FileName);
                    Baptismfile = Baptismfile + DateTime.Now.ToString("yymmssffff") + Baptismfileextension;
                    dcvm.BaptismUrl = Baptismfile;
                    Baptismfile = Path.Combine(Server.MapPath("~/Content/Images/"), Baptismfile);
                    dcvm.BCCert.SaveAs(Baptismfile);
                }
             
                var worker = new Worker
                {
                    BCUrl = dcvm.BCUrl,
                    BCCert = dcvm.BCUrl,

                    BaptismUrl = dcvm.BaptismUrl,
                    BaptismCert = dcvm.BaptismUrl,
                    WorkerName = dcvm.FirstName + " " + dcvm.LastName,
                    BaptismDate = dcvm.BaptismDate,
                    HolyGhostBaptism = dcvm.HolyGhostBaptism,
                    IsMarried = dcvm.IsMarried,
                    WaterBaptism = dcvm.WaterBaptism,
                    JoinDate = dcvm.JoinDate,
                    Address = dcvm.Address,
                    Department = dept,
                    ImageUrl = dcvm.ImageUrl,
                    ImageThumbnailUrl = dcvm.ImageUrl,
                    PhoneNumber = dcvm.PhoneNumber,
                    Experience = dcvm.Experience,
                    SODUrl = dcvm.SODUrl,
                    SODCert = dcvm.SODUrl,
                    SpouseName = dcvm.SpouseName,
                    NumberOfChildren = dcvm.NumberOfChildren,
                    MarriageAnniversary = dcvm.MarriageAnniversary,
                    Profession = dcvm.Profession,
                    ChurchBaptised = dcvm.ChurchBaptised,
                    BornAgain = dcvm.BornAgain,
                    YearBornAgain = dcvm.YearBornAgain,
                    IsExperienced = dcvm.IsExperienced,
                    BirthDate = dcvm.BirthDate,
                    SOD = dcvm.SOD,
                    SODYear = dcvm.SODYear,
                    SOM = dcvm.SOM,
                    SOMYear = dcvm.SOMYear,
                    BC = dcvm.BC
                };

                _uow.Workers.Add(worker);

                _uow.Commit();
                TempData["message"] = string.Format("{0} has been saved.", dcvm.FirstName);
                return RedirectToAction("Index", "Home");

            }
            else
            {
                var dept = _uow.Departments.GetAll().Select(r => r.Name);
                ViewBag.Department = new SelectList(dept);
                return View(dcvm);
            }
        }

    }
}

PAWeb/Views/Shared/AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Praise Assembly Ajah</title>
    <link rel="icon" href="~/Content/img/rccggood.png">
    <link href="~/Content/Login/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Content/Login/css/main.css" rel="stylesheet" />

</head>
<body>

    <div class="container body-content">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }


        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PraiseAssembly</p>
        </footer>
    </div>
    <script src="~/Content/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Content/Login/vendor/animsition/js/animsition.min.js"></script>
    <script src="~/Content/Login/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/Login/js/main.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("script2", required: false)
</body>
</html>

PAWeb/Views/Shared/_Footer.cshtml
 
<footer class="footer-area">
   
    <div class="main-footer-area">
        <div class="container">
            <div class="row">
                <div class=" col-md-6">
                    <p>Jesus Christ the same yesterday, and today, and for ever. <span>Hebrews 13 vs 8.</span></p>

                </div>
            </div>
            <div class="row">

              
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-70">
                        <a href="#" class="footer-logo"><img src="~/Content/img/rccggood.png" alt="" width="40" height="40">Praise Assembly</a>

                        <p>
                            We give God what he loves best becuase that is what we do best -PRAISE.
                            <br />
                            When our praises go up, God's presence comes down.
                        </p>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-70">
                        <h5 class="widget-title">Quick Link</h5>
                        <nav class="footer-menu">
                            <ul>
                                <li><a href="@Url.Action("Index","Home")"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Home</a></li>
                                <li><a href="@Url.Action("About","Home")"><i class="fa fa-angle-double-right" aria-hidden="true"></i> About</a></li>
                                <li><a href="@Url.Action("Index","Sermon")"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Sermon</a></li>
                                <li><a href="@Url.Action("DepartmentCorner","Department")"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Join Us</a></li>
                                <li><a href="@Url.Action("UpcomingEvents","Event")"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Events</a></li>
                                <li><a href="@Url.Action("Contact","Home")"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-70">
                        <h5 class="widget-title">Services</h5>

                       
                        <div class="single-latest-news">
                            <a href="#">Digging Deep </a>
                            <p><i class="fa fa-calendar" aria-hidden="true"></i> Tuesday 6:30pm</p>
                        </div>

                
                        <div class="single-latest-news">
                            <a href="#">Faith Clinic</a>
                            <p><i class="fa fa-calendar" aria-hidden="true"></i>Thursday 6:30pm</p>
                        </div>
                        <div class="single-latest-news">
                            <a href="#">Sunday Worship</a>
                            <p><i class="fa fa-calendar" aria-hidden="true"></i>Sunday 8:30a.m</p>
                            <p><i class="fa fa-clock-o" aria-hidden="true"></i>Thanksgiving sunday - First Sunday</p>
                        </div>

                    </div>
                </div>

              
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-70">
                        <h5 class="widget-title">Contact Us</h5>

                        <div class="contact-information">
                            <p><i class="fa fa-map-marker" aria-hidden="true"></i> No. 49 Shekoni Omokoku Street, Alfa Bus Stop, Sangotedo, Lagos State</p>
                            <a href="callto:001-1234-88888"><i class="fa fa-phone" aria-hidden="true"></i> 08060571803</a>

                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

  
    <div class="copywrite-area">
        <div class="container h-100">
            <div class="row h-100 align-items-center flex-wrap">
              
                <div class="col-12 col-md-6">
                    <div class="copywrite-text">
                        <p>
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved  <br />Praise Assembly
                        </p>
                    </div>
                </div>

               
                <div class="col-12 col-md-6">
                    <div class="footer-social-icon">
                        <a href="https://www.facebook.com/rccgpraiseajah" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="http://twitter.com/rccgpraiseajah" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="https://www.instagram.com/rccgpraiseajah" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

PAWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Praise Assembly | @ViewBag.Title</title>

   
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js"></script>
    <script src="~/Content/js/AngScript.js"></script>
    <link rel="icon" href="~/Content/img/rccggood.png">


    <link rel="stylesheet" href="~/Content/style.css">

</head>

<body ng-app="myModule">
    <div class="preloader d-flex align-items-center justify-content-center">
       
        <div class="line-preloader"></div>
    </div>
    @Html.Partial("_NavBar")



    @RenderBody()


    <div>
        @Html.Partial("_Footer")
    </div>

    <script src="~/Content/js/jquery/jquery-2.2.4.min.js"></script>

    <script src="~/Content/js/bootstrap/popper.min.js"></script>

    <script src="~/Content/js/bootstrap/bootstrap.min.js"></script>

    <script src="~/Content/js/plugins/plugins.js"></script>

    <script src="~/Scripts/sweetalert.min.js"></script>
    <script src="~/Content/js/active.js"></script>
    <script src="~/Content/countdown/js/jquery.countdown.min.js"></script>
    <script src="~/Content/js/DateCount.js"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>


    @RenderSection("scripts", required: false)
    @RenderSection("script2", required: false)
</body>
</html>

PAWeb/Views/Shared/_NavBar.cshtml
<header class="header-area">

    <div class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="top-header-content d-flex flex-wrap align-items-center justify-content-between">
                      
                        <div class="top-header-meta d-flex flex-wrap">
                            <a href="#" class="open" data-toggle="tooltip" data-placement="bottom"> <span>Praise Assembly</span></a>

                            <div class="top-social-info">
                                <a href="https://www.facebook.com/rccgpraiseajah" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="http://twitter.com/rccgpraiseajah" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="https://www.instagram.com/rccgpraiseajah" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>

                            </div>
                        </div>
                        
                        <div class="top-header-meta">
                            <a href="#" class="phone"><i class="fa fa-phone" aria-hidden="true"></i> <span>+234 806 057 1803 </span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
    <div class="crose-main-menu">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
             
                <nav class="classy-navbar justify-content-between" id="croseNav">

                    <a href="#" class="nav-brand">
                        <img src="~/Content/img/rccggood.png" alt="" width="40" height="40">
                        <span>PRAISE ASSEMBLY</span>
                    </a>

                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <div class="classy-menu">

                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <div class="classynav">
                            <ul>
                                <li>  @Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("Programme", "NationalProgramme", "Home")</li>

                                <li>
                                    <a href="#">Over View</a>

                                    <ul class="dropdown">
                                        <li>@Html.ActionLink("About", "About", "Home")</li>
                                        <li>@Html.ActionLink("Join Department", "JoinWorker", "Worker")</li>
                                        <li>@Html.ActionLink("Gallery", "Gallery", "Gallery")</li>
                                        <li><a href="@Url.Action("DepartmentCorner","Department")">Ministries</a></li>
                                    </ul>

                                </li>
                                @*<li>@Html.ActionLink("Events", "UpcomingEvents", "Event")</li>*@
                                <li>@Html.ActionLink("Sermon", "Index", "Sermon")</li>
                                <li> @Html.ActionLink("Login", "Login", "Account")</li>
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            </ul>

                            <div id="header-search"><i class="fa fa-search" aria-hidden="true"></i></div>


                        </div>
                   
                    </div>
                </nav>
            </div>
        </div>

        <div class="search-form-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="searchForm">
                            <form action="#" method="post">
                                <input type="search" name="search" id="search" placeholder="Enter keywords &amp; hit enter...">
                                <button type="submit" class="d-none"></button>
                            </form>
                            <div class="close-icon" id="searchCloseIcon"><i class="fa fa-close" aria-hidden="true"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
</header>